/**
 * @module Icons
 * @page index
 * @description Re-exports ícones do Lucide React para uso centralizado na aplicação.
 * @path src/icons/index.ts
 */

/* eslint-disable no-restricted-imports -- allowed here as this file re-exports icons for the rest of the app */
export {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Award,
  BarChart2,
  Bell,
  BookOpen,
  Building2,
  Calendar,
  CalendarClock,
  CalendarDays,
  CalendarPlus,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  ClipboardList,
  ClipboardPen,
  Clock,
  Clock3,
  Code2,
  Copy,
  FileDown as Download,
  Edit2 as Edit,
  Edit2,
  ExternalLink,
  Eye,
  EyeOff,
  FileBarChart2,
  FileDown,
  FileText,
  Filter,
  GitMerge,
  Hash,
  HelpCircle,
  Info,
  Key,
  LayoutDashboard,
  LayoutGrid,
  LayoutList,
  ListChecks,
  Loader2,
  LogOut,
  Mail,
  MapPin,
  Menu,
  MinusCircle,
  MoreHorizontal,
  Phone,
  Plane,
  Plus,
  Printer,
  Save,
  Search,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Tag,
  Ticket,
  Timer,
  Trash2,
  TrendingUp,
  User,
  UserCheck,
  UserCircle2,
  Users,
  UserX,
  View,
  X,
  XCircle,
} from "lucide-react";

export type { LucideIcon, LucideProps } from "lucide-react";
