/* eslint-disable no-restricted-imports -- allowed here as this file re-exports icons for the rest of the app */
export {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Award,
  BarChart2,
  Bell,
  BookOpen,
  Building2,
  Calendar,
  CalendarClock,
  CalendarDays,
  CalendarPlus,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  ClipboardList,
  ClipboardPen,
  Clock,
  Clock3,
  Copy,
  FileDown as Download,
  Edit2,
  ExternalLink,
  Eye,
  EyeOff,
  FileBarChart2,
  FileDown,
  FileText,
  Filter,
  GitMerge,
  Hash,
  HelpCircle,
  Info,
  Key,
  LayoutDashboard,
  LayoutGrid,
  LayoutList,
  ListChecks,
  Loader2,
  LogOut,
  MapPin,
  Menu,
  MinusCircle,
  MoreHorizontal,
  Plane,
  Plus,
  Printer,
  Save,
  Search,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Ticket,
  User,
  UserCheck,
  Users,
  UserX,
  X,
  XCircle,
} from "lucide-react";

export type { LucideIcon, LucideProps } from "lucide-react";
